### ISSUE TITLE
Allow Empty Keys to Be Bypassed Without Error

### ISSUE THREAD

**Issue by jhoover4** [IBM/argocd-vault-plugin#165]
**Is your feature request related to a problem? Please describe.**
My use case is that we store all of our secrets in one vault config for each environment. For some of these environments (say dev), a key may not have been created and the existence should be optional. Using the plugin makes having a value for these keys required.

**Describe the solution you'd like**
I'd like to have an annotation that can be used to configure the default behavior and not error out if a key is missing, instead merely give a warning.

**Describe alternatives you've considered**
I haven't thought of other solutions but open to ideas!

Perhaps our way of keeping these keys in vault is not ideal, but I do think I'd rather us not have to have blank values in vault for some of these keys (or have to keep track of it).

**Additional context**
Example of current behavior of the plugin that I'd like to change:

![Screen Shot 2021-07-14 at 12 21 56 PM](https://user-images.githubusercontent.com/20507620/125665389-1528ccc2-51ae-4121-a01e-cc714494b258.png)

I'd also be happy to contribute a PR for this, but I wanted to make sure the feature is okay with the maintainers first or if there's a reason it may not be needed.

**Comment by jkayani** [comment]
@jhoover4 Interesting. When you say:

> I'd like to have an annotation that can be used to configure the default behavior and not error out if a key is missing, instead merely give a warning.

What should happen with the placeholder? I assume it should just remain there as-is? I think the behavior you're asking for is certainly doable, something like `avp.kubernetes.io/ignore-missing-placeholders: true`. I'd be curious as to @werne2j 's thoughts on this. 

Also I'm not sure how useful that warning would be (at least in the context of ArgoCD) since to my knowledge the stderr of an ArgoCD plugin is never displayed in the UI (but maybe it appears in the repo-server pod logs? not sure). If this is a use-case not involving ArgoCD then my point is moot here.

**Comment by jhoover4** [comment]
I was thinking to just skip the placeholder altogether. Either that or we can have a null value we always use?

Yeah I think not having a warning would make sense, it would probably just be junk if you knew what you were doing.

You do see the stderr by the way if the plugin errors out. Its available when you look at the errors under the application.

**Comment by werne2j** [comment]
@jhoover4 

> I was thinking to just skip the placeholder altogether.

If by this you mean to leave the placeholder in the file we can do that, however, if you have:
```
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: project/sets/data/test-secret
    avp.kubernetes.io/allow-empty: true     # or whatever
data:
 secret: <some-value>
type: Opaque
```
and we skip the placeholder, there will still be an error as that is not valid kubernetes yaml. So that would be a situation you would have to handle yourself.

I guess the other option of filling the placeholder with an empty value is also possible. I like to limit the amount of manipulation the plugin does. I prefer it to simply do its task of replacing. But i am open if this is a common use case.

**Comment by jhoover4** [comment]
Hey @werne2j yeah I think it would just skip them completely. The other way I was thinking would have a placeholder you define like you said. I think skipping them seems easier for sure.

I also understand not wanting to have feature bloat for sure. Can't say how common the use case is, but this would be helpful to us for sure. I think its a pretty easy addition.

**Comment by jhoover4** [comment]
@werne2j @jkayani this is becoming a big issue for us. Think this is something I could open a PR for?

**Comment by werne2j** [comment]
@jhoover4 Sorry we have not been able to get to this but you can definitely submit a PR!

**Comment by jhoover4** [comment]
Awesome! Just opened the PR, let me know what you think!
