### ISSUE TITLE
Authentication to Vault failed

### ISSUE THREAD

**Issue by gracenng** [IBM/argocd-vault-plugin#170]
**Describe the bug**
After setting up, when creating an application on ArgoCD, application cannot be created with error message: 
`Put "http://127.0.0.1:8200/v1/auth/approle/login": dial tcp 127.0.0.1:8200: connect: connection refused`

I used `curl` with the `role-id` and `secret-id` that was used as AVP env variable in the `argocd-vault-plugin-credentials` secret. The approle has been configured to have unlimited number of usage, and ttl=0.  Here, it is in payload.json.

```
grace@ws2:~/code/learning$ curl     --request POST     --data @payload.json     http://127.0.0.1:8200/v1/auth/approle/login | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   594  100   487  100   107   7730   1698 --:--:-- --:--:-- --:--:--  9428
{
  "request_id": "<request-id>",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": null,
  "wrap_info": null,
  "warnings": null,
  "auth": {
    "client_token": "<client-token>",
    "accessor": "<accessor>",
    "policies": [
      "default",
      "internal-app"
    ],
...
}
```
I have also verified that my approle is tied to a proper Vault policy and successfully retrieved  with the secret path using `curl`. The Vault URL is up during this time and Vault address found using the `VAULT_ADDR` variable inside the vault pod.

**To Reproduce**
1. Set up Vault
2. Follow the repo's Medium [article](https://itnext.io/argocd-secret-management-with-argocd-vault-plugin-539f104aff05)

**Expected behavior**
ArgoCD is able to create an application

**Screenshots**
<img src="https://user-images.githubusercontent.com/42276283/127661631-71582760-80b0-4d83-a905-5971111f4df2.png" height="500">
**Additional context**
N/a

**Comment by saloyiana** [comment]
Facing the same issue, any hints?

**Comment by werne2j** [comment]
@gracenng where is your Vault running? 

When you use `127.0.0.1` in Kubernetes, it is not the same as `127.0.0.1` on your machine. There are ways you could set that up but running Vault in Kubernetes makes things a little easier. 

If you run Vault in Kubernetes, you'd want to try and connect via the service Kubernetes service. So instead of `127.0.0.1:8200` you'd have something like `vault.vault-namespace:8200` Here are some docs on running Vault on Kubernetes: https://www.vaultproject.io/docs/platform/k8s/helm/run. 

If you ran AVP outside of Argo CD and Kubernetes connecting to `127.0.0.1:8200` i am betting it would work. So it's not an AVP issue but an issue of being able to access something on a localhost from inside a cluster.

**Comment by jkayani** [comment]
To add to the above, where did you run the `curl` test? If you ran it from a shell on your machine, that's not a representative test, since `localhost` and the k8s network are distinct (even if you're running k8s locally) - you should try running the test from a pod in your k8s cluster. You can use something like the `busybox` image to do that. If you do this test from another pod in your cluster and get a failure to connect to Vault, I'd conclude AVP is _not_ the cause of your problem.

**Comment by gracenng** [comment]
Thank you both, I'll give that a try. I was running `curl` from my local shell and Vault is on my cluster

**Comment by gracenng** [comment]
Hi there,

I am using version 0.3
I was able to start the `argocd` application but the secret is not being injected. 
```
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp_path  : "internal/data/config"
type: Opaque
stringData:
  sample-secret: <username>
```
I was able to take @jkayani suggestion and `curl` the secret from this path with the token of this approle from an alpine pod:
```
curl --header "X-Vault-Token:<approle-client-token>" http://<vault-url>/v1/internal/data/config | j
q .
{
  "request_id": "<request-id>",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "data": {
      "username": "password"
    },
...
```
When I get the secret created, it's just the encoded version of the "<username>" I put in. I'm quite confused as the curl from pod worked and the process was quite smooth so it's hard to debug.
Any pointers appreciated

**Comment by werne2j** [comment]
@gracenng If the secret is being applied with an encoded `<username>` then that probably means that AVP is not actually running. I would check to make sure your application is using AVP as the custom plugin. 

That being said, version 0.3.0 is very old and i recommend upgrading to 1.x.

**Comment by werne2j** [comment]
Can you run AVP as a CLI outside of Argo CD with yamls and see if that works? If so, then there is most likely a configuration issue on your setup in Argo CD

**Comment by gracenng** [comment]
Thanks for the speedy reply @werne2j .
- I checked the argocd-repo-server pod and the avp CLI was functional, and I chose AVP as the plugin on the UI. Did I miss anything here?
- I upgraded AVP inside the cluster and got the same locally, `version 1.1.0` and updated the annotations accordingly. I'm now facing a new error: `"https://127.0.0.1:8200/v1/auth/approle/login": dial tcp 127.0.0.1:8200: connect: connection refused`

I do not have `127.0.0.1:8200` configured anywhere. The `argocd-repo-server` and `argocd-server` pods were restarted after the config secret is deployed.
This error also occurs locally with config file same as before, where `VAULT_ADDR` is the pod IP

I also put `AVP_VAULT_ADDR` as an ENV variable in the plugin UI but the same error persists.

Sorry for the bother and thank you for your help

**Comment by werne2j** [comment]
@gracenng for 1.x AVP_VAULT_ADDR was changed to VAULT_ADDR

**Comment by gracenng** [comment]
Working now, thank you very much!

**Comment by werne2j** [comment]
Glad you got it working!
