### ISSUE TITLE
Add concurrency to IBM and Azure backends

### ISSUE THREAD

**Issue by werne2j** [IBM/argocd-vault-plugin#207]
In both IBM Secrets Manager and Azure we are having to loop through many individual secrets. This causes those backends to have poor performance compared to the other backends.

We want to implement concurrency into those backends to improve the performance.

**Comment by jkayani** [comment]
Instead of making as-is Azure concurrent, why don't we:

- Add `GetIndividualSecret(path secret version string) (map[string]interface{}, error)` method to backend interface
- For all backends but Azure, have that method just use `GetSecrets` and strip the result down to a map of length 1 with desired value
- For Azure specifically, have GetIndividualSecret call `azureSDK.Client.GetSecret` with the name and version from the placeholder. Nothing else. No goroutines in the Azure backend.

End result: All the backends perform similarly (see below comment): Azure and GCP in 1 group, AWS and plain Vault in another. IBM SM on its own.  The generic placeholders with Azure will still be slow if having to retrieve a specific secret version via the annotation, but that use-case would almost never happen because versions are unique among the secrets (placeholders), so using the annotation is rarely useful. But all backends are setup to later improve inline-path performance by doing each replacement in an individual goroutine (if needed). 

I would prefer to do this than try to add concurrency to the Azure setup as-is because as-is is a weird situation where `GetSecrets` does not know the `secret` name, so when replacing a placeholder like `<path:my-azure-kv#key#version3>` we have to loop through all the secrets in `my-azure-kv` and all the versions of each secret to find `key` and its value, rather than getting it directly. Adding concurrency to this will be more complicated since the goroutines would have to communicate with each other to know when to "end the search" and the "search" itself is a really inefficient way of handling inline-path placeholders.

**Comment by jkayani** [comment]
With plain Vault, the path is a group of secrets you can retrieve all at once. No extra cost for versioning
- Generic placeholders require **1 call per file**
- inline-path just requires 1 per placeholder per file => **N per file**. 

The next logical way to speed this up is to introduce goroutines in the kube package rather than just in backends, handling each inline-path placeholders replacement in a goroutine

With IBM SM, the path is a group of secrets, but you have to retrieve each individually, and you can't retrieve them by placeholder (name) => you have to loop through the group to find the ones you want. No versioning supported right now.
- Generic requires 1 call to list per file, N calls for each placeholder => **N + 1 calls per file**. 
- Inline-path requires 1 call to list per placeholder/group, Y calls for each group member => **NY calls per file**. 

So goroutines were very helpful here: we handle each N sequentially, but each Y concurrently. Doing each N concurrently means same as speeding up plain Vault.

With GCP, the path is specific to just one secret. No extra cost for versioning. 
- Generic needs 1 call per placeholder => **N per file**. 
- Inline-path requires 1 call per placeholder => **N per file**. 

AWS is like plain Vault: secrets that contain k/v pairs. (technically also you can have secrets with just values like GCP, but we don't support that). No extra cost for versioning. 
- Generic needs **1 per file**
- inline-path **N per file**

With Azure, the path is just a whole instance, so a a group of secrets. You have to retrieve each individually. But you can retrieve an individual one by name  - we don't do that right now in the case of inline-path placeholders, but if we did, then 

- Generic would need 1 call to list secrets in the path (instance) per file, 1 call per placeholder (plus 1 more to get a specific version) => at most **2N + 1 per file**
- Inline-path would just need 1 call per placeholder (version specified or not) => **N per file**

**Comment by jkayani** [comment]
*Tangential thought*

I also wonder if we should cache data during an AVP run - if the same inline-path placeholder appears in multiple places/files (or if the same generic placeholder + path annotation + secret version annotation appears in multiple files), we call out to the SM backend for the same data every time. Probably not a common scenario but seems like it might be worthwhile

**Comment by werne2j** [comment]
@jkayani i am fine with this. Something i mentioned wanting to do in the past. In summation, yes to `GetIndividualSecret `.

**Comment by werne2j** [comment]
Released with https://github.com/IBM/argocd-vault-plugin/releases/tag/v1.4.0
