### ISSUE TITLE
Use of config file

### ISSUE THREAD

**Issue by werne2j** [IBM/argocd-vault-plugin#32]
We want to allow the use of a config file instead of just environment variables for things like vault path, vault path, auth type, etc. May want to look into https://github.com/spf13/viper for accomplishing this.

**Comment by jkayani** [comment]
Viper looks like a good choice, since it will abstract away where the config comes from (env variable or config file). 

It seems that normal use involves reading config files from disk; however, in our usage, we want to read YAMLs embedded in Kubernetes secrets right (since the full configuration will contain credentials)? In that case, should we expect users to mount their secret in a certain file path in their argocd-repo-server, and read it that way? Or maybe just have the user mount the secret as file somewhere in the repo server, and then have them pass the path to the configuration as a command line argument when invoking the plugin?

I'm mentioning mounting secrets as files so that we don't have to ask the ArgoCD server's Kubernetes API for that secret's value (and therefore  deal with permissions and a service account), and so that we easily allow for config-as-a-file for non-ArgoCD users.

**Comment by werne2j** [comment]
I think we should allow passing a config file to the cli via a path for sure.

However, I’m not sure we wouldn’t be able to read a secret directly from kubernetes though as we are inside the Argo repo server pod which should already have the permissions we would need.

**Comment by jkayani** [comment]
You're right - I keep forgetting this is a binary running in a pod, not another pod itself. Question still remains though, is it sufficient to accept a config file via CLI, use Viper to combine that info with any environment variables to create a configuration we use in the app, and expect people who want to store their config files in Kubernetes to use volume mounts? 

Or should we accept both a config file argument or the name of a Kubernetes secret in the current namespace, and in case of the latter, call the API to get the secret data?

**Comment by werne2j** [comment]
> Or should we accept both a config file argument or the name of a Kubernetes secret in the current namespace, and in case of the latter, call the API to get the secret data?

This

**Comment by jkayani** [comment]
Last question - now that we have Viper, we can map multiple env variables to a single config parameter easily. So this would allow for us to read a user's IBM Cloud API key from multiple possible env variables, with a precedence - should we use this to allow things like `AVP_IBM_API_KEY` as well as something more generic and accepted by other tools, like `BX_API_KEY`?

**Comment by werne2j** [comment]
I guess i will leave that up to you. I decided on use the `AVP` prefix so we could have things isolated and scoped. But if you think that is a good idea, go for it.

**Comment by jkayani** [comment]
In case anyone is reading this, I chose not to fall back to other environment variable names for the config parameters. If you want this, open another issue :)
