### ISSUE TITLE
Option to ignore if no secret for type found

### ISSUE THREAD

**Issue by jamesmmchugh** [IBM/argocd-vault-plugin#54]
**Is your feature request related to a problem? Please describe.**
The plugin tries to find secrets by appending the resource type to the path_perfix. If, however, you have no secrerts for a particular resource/resource type then you get errors like the following (using a namespace as the example):

```
Error making API request.

URL: GET http://<vault_server>/v1/namespace
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

**Describe the solution you'd like**
For the plugin to ignore resources that have no secrets templated and simply output them as they aer

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jkayani** [comment]
Hi,

To confirm, you believe that in the scenario where you have a YAML like:

```
kind: ConfigMap
data:
 hello: world
```

in a folder that you are processing via the plugin, and there is no Vault secret at `${PATH_PREFIX}/configmap` the plugin should simply output the file as-is, right? If so, that makes sense to me. 

But what about this scenario? A YAML like:

```
kind: ConfigMap
data:
 hello: <world>
```

where someone forgets to create the Vault secret at `${PATH_PREFIX}/configmap` - then I guess you'd want to see an explicit 4xx where the plugin tried to replace `<world>`, instead of seeing an error trying to apply a YAML with `<world>` literally in it. Right?

If so, I think the desired behavior altogether is:

- If a given `Template` (YAML) has placeholders, and Vault returns an error trying to retrieve data for it, return that error so the user has a hint on how to fix it (create an entry in Vault for that resource or remove the `<placeholder>'s`)

- If a given `Template` has _no_ placeholders, emit the YAML as-is

**Comment by jkayani** [comment]
Sorry if the above seems long-winded, I'm trying to keep in mind the exact logic the code needs to follow after fixing this

**Comment by jamesmmchugh** [comment]
Yes, that's exactly what I think the behaviour should be also:

No templated variables, no secret = no error and output as-is

Templated variables, no secret = error (4xx)

Currently I'm working around it by putting all resources with secrets in a
different application in argocd, but it's not ideal in terms of project
structure.

**Comment by vmwiz** [comment]
I'm getting the same kind of error

```
Error making API request. 
URL: GET https://<vault server>/v1/namespace
Code: 403. Errors: 
  * 1 error occurred: 
      * permission denied
```

The templated value is an environment variable inside a `Deployment` ressource.

Can somebody explain to me why the plugin would want to render a `Namespace` resource where there is no placeholder defined for that resource? And why there is a call to `https://<vault server>/v1/namespace` ?

Before finding this issue I thought the plugin was trying to read the Vault namespaces (enterprise feature)

**Comment by werne2j** [comment]
@vmwiz The way the code was originally written was to take the `AVP_PATH_PREFIX` environment variable and then append the resource kind to that to create an opinionated path for putting secrets. `https://<vault server>/v1/AVP_PATH_PREFIX/namespace`. And this runs for all resource. We see that we should take into account resources that do not have placeholders and not try to pull anything from Vault. This is a fix that we are currently working on. Please bear with us 🙂

**Comment by jkayani** [comment]
> Currently I'm working around it by putting all resources with secrets in a
different application in argocd, but it's not ideal in terms of project
structure.

Until we fix this (which should be soon), @jamesmmchugh has provided the above workaround. The comment before that explains the logic we will implement to fix the problem: 

> If so, I think the desired behavior altogether is:
If a given Template (YAML) has placeholders, and Vault returns an error trying to retrieve data for it, return that error so the user has a hint on how to fix it (create an entry in Vault for that resource or remove the <placeholder>'s)
If a given Template has no placeholders, emit the YAML as-is

Please be patient!

**Comment by werne2j** [comment]
A fix has been published in https://github.com/IBM/argocd-vault-plugin/releases/tag/v0.4.0
