### ISSUE TITLE
Investigate supporting other secret types for IBM Cloud Secrets Manager

### ISSUE THREAD

**Issue by werne2j** [IBM/argocd-vault-plugin#73]
Currently we only support Arbitrary secrets for IBM Cloud Secrets Manager. 
We should look into how we could possibly support Username/password along with Arbitrary.

This would require some ability to specify the username or password field in the `<placeholder>` or assume a certain naming convention for the secret keys.

**Comment by jkayani** [comment]
With #189 we migrated to using the IBM SM REST API instead of the Vault based API which makes supporting non-arbitrary types a bit easier. Most of the code is in place - it's just a matter of being able to figure out which specific item from a non-arbitrary secret (e.g, public cert in `imported_cert`, username in `username_password`) is needed for a `<placeholder>`

Maybe the placeholder key syntax could be extended to be a JSON path that would be used on the JSON inside `SecretData`: https://github.com/json-path/JsonPath#operators. Something like `<my-secret.username>` for `username_pasword` or `<path:bmcloud/arbitrary/MYGROUP#my-cert.private_key#v3>` for `imported_cert`.  

Unf. the IBM SM API returns the actual data in a `SecretData` field only _most_ of the time - for some reason `IamCredentialSecretResource` is different and just has an `APIKey` field with the data, no `SecretData`: https://cloud.ibm.com/apidocs/secrets-manager?code=go#get-secret So we'd have to handle this differently than just interpreting the placeholder as a JSON path since the JSON we'd query doesn't exist. 

To make this backwards compatible with how IBM SM worked, we'd have to assume `$.payload` as the JSON path when using `<placeholder>` or `<path:ibmcloud/arbitrary/MYGROUP#key>` or `<path:ibmcloud/arbitrary/MYGROUP#key#version>`. 

To make this compatible with _other_ secret managers, I think it'd just be a matter of trying to interpret the secret's value as a JSON string if a placeholder with a JSON path is present, and if failing, throwing an error.

**Comment by jkayani** [comment]
Released here: https://github.com/IBM/argocd-vault-plugin/releases/tag/v1.5.0
